spring:
  application:
    name: mounting-systems-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /mounting
  endpoint:
    prometheus:
      enabled: true
