spring:
  application:
    name: mounting-systems-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083

management:
  endpoints:
    web:
      base-path: /mounting/actuator
      exposure:
        include: "*"
