global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'spring-boot-app-bff'
    metrics_path: /bff
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'spring-boot-app-auxiliary'
    metrics_path: /auxiliary
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'spring-boot-app-control-system'
    metrics_path: /control-system
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'spring-boot-app-engine'
    metrics_path: /engine
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'spring-boot-app-mounting'
    metrics_path: /mounting
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'spring-boot-app-power'
    metrics_path: /power
    static_configs:
      - targets: ['host.docker.internal:8084']

  - job_name: 'spring-boot-app-registry'
    metrics_path: /registry
    static_configs:
      - targets: ['host.docker.internal:8761']
