spring:
  application:
    name: engine-systems-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

management:
  endpoints:
    web:
      base-path: /engine/actuator
      exposure:
        include: "*"
