spring:
  application:
    name: engine-systems-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /engine
  endpoint:
    prometheus:
      enabled: true
