spring:
  application:
    name: bff-service
  kafka:
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true

server:
  port: 8085

management:
  endpoints:
    web:
      base-path: /bff/actuator
      exposure:
        include: "*"