spring:
  application:
    name: bff-service
  kafka:
    bootstrap-servers: localhost:29092
  h2:
    console:
      enabled: true

server:
  port: 8085

redis:
  host: localhost
  port: 6379

management:
  endpoints:
    web:
      base-path: /bff/actuator
      exposure:
        include: "*"