spring:
  application:
    name: auxiliary-systems-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /auxiliary/actuator
      exposure:
        include: "*"
