spring:
  application:
    name: auxiliary-systems-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /auxiliary
  endpoint:
    prometheus:
      enabled: true