spring:
  application:
    name: control-systems-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /control-system/actuator
      exposure:
        include: "*"
