spring:
  application:
    name: control-systems-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /control-system
  endpoint:
    prometheus:
      enabled: true