spring:
  application:
    name: power-transmission-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8084

management:
  endpoints:
    web:
      base-path: /power/actuator
      exposure:
        include: "*"
