spring:
  application:
    name: power-transmission-service
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /power
  endpoint:
    prometheus:
      enabled: true
